version: '3.8'

services:
    backend:
        image: ecommerce
        build: .
        ports:
            - 80:80
        volumes:
            - ./:/app
        env_file:
            - ./.env.example
        depends_on:
            - mongodb

    mongodb:
        image: mongo
        container_name: mongodb
        volumes:
            - ./data:/data/db
        ports:
            - 27017:27017

    mongo-express:
        image: mongo-express
        container_name: mongo-express
        environment:
            ME_CONFIG_MONGODB_SERVER: mongodb
            ME_CONFIG_MONGODB_PORT: '27017'
        ports:
            - 8081:8081
        depends_on:
            - mongodb
